# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to my personal server - ika-namez

on:
  push:
    branches:
      - api
  workflow_dispatch:

jobs:
  deploy-to-ika-namez:
    runs-on: ubuntu-latest

    steps:
      - name: install-ssh
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: adding-known-hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm-actions
        run: |
          yarn install
          yarn run compile

      - name: change-compiled-to-javascript
        run: |
          ls
          rm -r ./src
          cp -r ./build/src ./src

      - name: create-env-file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_PORT: ${{ secrets.API_PORT }}
          envkey_API_ALLOWED_HOST: ${{ secrets.API_ALLOWED_HOST }}

      - name: stop-pm2-service
        continue-on-error: true
        run: |
          ssh  -i /home/runner/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} 'pm2 stop ika-namez'

      - name: remove-old-stuff
        continue-on-error: true
        run: |
          ssh  -i /home/runner/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} 'rm -r ika-namez/ && mkdir -p ika-namez'

      - name: deploy-with-rsync
        run: rsync -avz ./ ubuntu@${{ secrets.SSH_HOST }}:/home/ubuntu/ika-namez/

      - name: start-pm2-service
        continue-on-error: true
        run: |
          ssh  -i /home/runner/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} 'pm2 start ika-namez'
